### ISSUE TITLE
Rotate device: Background image is not present 

### ISSUE THREAD

**Issue by computangit** [computangit/Skinn.com-#1]
**URL tested:** https://skinn.com/

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fskinn.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://skinn.com/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone XS |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in - 2.79 x 5.65 in |
| Viewport | 375 x 812 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/d38f06ce694bc66874ab7781e7bb6d6f141a28a0/realios_iPhone_XS.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/d38f06ce694bc66874ab7781e7bb6d6f141a28a0/realios_iPhone_XS.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=iOS&os_version=12.0&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fskinn.com%2F&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://skinn.com/&utm_campaign=bug-report&utm_source=bug-report-url-to-reproduce&utm_medium=github) to reproduce the issue on Browserstack**

**Comment by farhan-arshad-com** [comment]
Verify and closed
